Algoritmo "loginesenha"

Var
login, senha:caractere
loginarmazenado, senhaarmazenada:caractere
Inicio


escreva("crie seu usuario:")
leia(loginarmazenado)
escreva("crie sua senha:")
leia(senhaarmazenada)

escreval("digite o login:")
leia(login)
escreval("digite a senha:")
leia(senha)

limpatela

se (login = loginarmazenado) e (senha = senhaarmazenada) entao
   escreval("bem-vindo")
senao
   escreval("login ou senha incorreta")
fimse




fimalgoritmo


 

